# Full reference https://github.com/gakonst/foundry/tree/master/config

[default]
auto_detect_solc = false
libs = ["lib"]
optimizer = true
optimizer_runs = 800
out = "out"
solc = "0.8.13"
src = "src"
test = "test"